from enum import Enum

class Model(Enum):
    MODEL = 'MODEL'
    BEST_PARAMETER = 'BEST_PARAMETER'

class Date(Enum):
    DATE = 'DATE'

class Data(Enum):
    TRAIN_INPUT_DATA = 'TRAIN_INPUT_DATA'
    TRAIN_OUTPUT_DATA = 'TRAIN_OUTPUT_DATA'
    VALID_INPUT_DATA = 'VALID_INPUT_DATA'
    VALID_OUTPUT_DATA = 'VALID_OUTPUT_DATA'
    TEST_INPUT_DATA = 'TEST_INPUT_DATA'
    TEST_OUTPUT_DATA = 'TEST_OUTPUT_DATA'
    PREDICTED_OUTPUT_DATA = 'PREDICTED_OUTPUT_DATA'

class Rmse(Enum):
    VALID_RMSE = 'VALID_RMSE'
    BEST_RMSE = 'BEST_RMSE'
    MOVING_RMSE = 'MOVING_RMSE'
    BEST_MAE = 'BEST_MAE'
